before_script:
  - apt-get update -qq
  - apt-get install -qq git
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - export DIR=$(date +%Y%m%d_%H%M%S)

deploy_server1:
  stage: deploy
  script:
    - ssh $SSH_USER@$SERVER "cd /var/www/test &&
      git clone https://github.com/OzyAst/PHP $DIR &&
      sudo chown www-data:www-data $DIR -R &&
      cd $DIR &&
      sh ./deploy.sh $SERVER &&
      cd .. &&
      ( [ ! -d /var/www/demo/current ] || mv -Tf /var/www/demo/current /var/www/demo/previous ) &&
      ln -s /var/www/demo/$DIR /var/www/demo/current"
  only:
    - master